#!/bin/bash
DIR_COMPOSE="$(dirname "$0")"/.compose
export DEPLOY_OWNER=$("$DIR_COMPOSE"/.DAC/sourceowner.sh)
export DEPLOY_GROUP=$("$DIR_COMPOSE"/.DAC/sourcegroup.sh)
COMPOSE_PROJECT_NAME="$("$DIR_COMPOSE"/.project/composeNameGet.sh up)"
export TRACE_SERVICE_PORT="$("$DIR_COMPOSE"/.port/trace/get.sh)"
"$DIR_COMPOSE"/.docker/compose/docker-compose --project-name="$COMPOSE_PROJECT_NAME" --project-directory="$DIR_COMPOSE" "$@"