version: "3.9"
services:
  base:
    image: debian:9.4
  idebase:
    image: idebase
    build:
      context: ./service/idebase/context/
      args:
        VER_DEBIAN: 9.4
        PKG_NAME_VER_VSCODE: code=1.60.2-1632313585
        ACCOUNT_VSCODE_OWNER_ID: ${PROJECT_FILES_OWNER}
        ACCOUNT_VSCODE_GROUP_ID: ${PROJECT_FILES_GROUP}
    depends_on:
    - base
  idego:
    image: idego
    build:
      context: ./service/idego/context/
    depends_on:
    - idebase
