version: "3.9"
services:
  idego:
    image: idego
    environment:
      DISPLAY: unix$DISPLAY
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ../../../
        target: /home/user/project
